### ISSUE TITLE
can't start iperf on minNExt

### ISSUE THREAD

**Issue by wenhuizhang** [USC-NSL/miniNExT#5]
Hi, while I was trying to run iperf on your app, it showed up as, is there something wrong with my set up please?
"mininext> iperf 
**\* Iperf: testing TCP bandwidth between a1 and exabgp
waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf to start up...waiting for iperf t"

**Comment by bschlinker** [comment]
Please execute iperf manually (a1 iperf exabgp), instead of using the mininext cmd

**Comment by wenhuizhang** [comment]
Thank you so much for your instructions, it seems that the more "manual" it is, the faster the result pops up, e.g."a1 iperf -c 140.0.0.1 -B 100.0.0.1 -p 4321 -t 2 " seems to be supporting faster processing than "a1 iperf -c exabgp" alike, which still takes a long time and then returns "**\* Iperf: testing TCP bandwidth between a1 and exabgp  \  waiting for iperf to start up...", Thank you so much for your instructions again, that is real helpful !
