### ISSUE TITLE
Policy for each autonomous system

### ISSUE THREAD

**Issue by Madhu94** [USC-NSL/miniNExT#6]
How should I create a separate  policy file for each autonomous system?

**Comment by bschlinker** [comment]
Hi @Madhu94 

I'm afraid I don't quite understand your question. Are you asking how we have separate BGP configuration files for each AS? We accomplish this by performing a bind mount over `/etc/quagga` in each container. This allows each container to have its own Quagga config files.

If I've misunderstood your question, let me know.

**Comment by Madhu94** [comment]
Yes, that was what I was asking. I have not worked much with Linux-based operating systems so I don't really understand your answer. Where could I look up the things I need to understand this project-
-how to create these Quagga conf files,independent policies for each participant, etc?
Thank you!
